name: blagenda_flutter_simple
description: Blagenda But Simple
version: 1.0.0+1

environment:
  sdk: '3.4.1'

dependencies:
  flutter:
    sdk: flutter

  #https://pub.dev/packages/http/install
  http: ^1.2.0
  # https://pub.dev/packages/date_format/example
  date_format: ^2.0.7
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.2

  permission_handler: ^11.3.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - icons/
  fonts:
   - family: JetbrainsMonoNL
     fonts:
      - asset: fonts/JetBrainsMono-Regular.ttf
      - asset: fonts/JetBrainsMono-Bold.ttf
        weight: 700
  uses-material-design: true

